// Generated by tools/owner/assets.py. Explicit URLs let Vite emit both app bundles.
export const OWNER_ASSETS: Record<string, { certificate: { pdf: string; preview: string }; inspection: string }> = {
  'CPB-001': {
    certificate: {
      pdf: new URL('./cpb-001-certificate.pdf', import.meta.url).href,
      preview: new URL('./cpb-001-certificate.png', import.meta.url).href,
    },
    inspection: new URL('./cpb-001-inspection.png', import.meta.url).href,
  },
  'CPB-002': {
    certificate: {
      pdf: new URL('./cpb-002-certificate.pdf', import.meta.url).href,
      preview: new URL('./cpb-002-certificate.png', import.meta.url).href,
    },
    inspection: new URL('./cpb-002-inspection.png', import.meta.url).href,
  },
  'CPB-003': {
    certificate: {
      pdf: new URL('./cpb-003-certificate.pdf', import.meta.url).href,
      preview: new URL('./cpb-003-certificate.png', import.meta.url).href,
    },
    inspection: new URL('./cpb-003-inspection.png', import.meta.url).href,
  },
  'CPB-004': {
    certificate: {
      pdf: new URL('./cpb-004-certificate.pdf', import.meta.url).href,
      preview: new URL('./cpb-004-certificate.png', import.meta.url).href,
    },
    inspection: new URL('./cpb-004-inspection.png', import.meta.url).href,
  },
  'CPB-005': {
    certificate: {
      pdf: new URL('./cpb-005-certificate.pdf', import.meta.url).href,
      preview: new URL('./cpb-005-certificate.png', import.meta.url).href,
    },
    inspection: new URL('./cpb-005-inspection.png', import.meta.url).href,
  },
  'CPB-101': {
    certificate: {
      pdf: new URL('./cpb-101-certificate.pdf', import.meta.url).href,
      preview: new URL('./cpb-101-certificate.png', import.meta.url).href,
    },
    inspection: new URL('./cpb-101-inspection.png', import.meta.url).href,
  },
};
