"""Create owner demo originals and exact PDF preview images. No real certification.

Run: python tools/owner/assets.py --font /path/to/Korean-font.ttf
Requires reportlab, Pillow, pypdf and Poppler (pdftoppm).
"""

import argparse
import json
from pathlib import Path
import subprocess
import tempfile

from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from pypdf import PdfReader

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'packages/mock/src/assets/owner'


def document(path, device, inspection=False):
    c = canvas.Canvas(str(path), pagesize=A4, invariant=1)
    c.setTitle(f'{device} 시연용 ' + ('비파괴 검사 성적서' if inspection else '제작증'))
    c.setAuthor('BoomEyes demo')
    w, h = A4

    def text(x, y, value, size=11, color='#172D39'):
        c.setFillColor(color)
        c.setFont('Korean', size)
        c.drawString(x, y, value)

    c.setFillColorRGB(0.94, 0.96, 0.96)
    c.rect(0, h - 170, w, 170, fill=1, stroke=0)
    text(44, h - 48, 'BOOMEYES  /  EQUIPMENT RECORD', 10)
    text(44, h - 92, '비파괴 검사 성적서' if inspection else '장비 제작증', 28)
    text(44, h - 126, f'{device}  ·  콘크리트 타설 붐', 14)
    text(44, h - 150, '시연용 샘플 - 실제 인증 또는 검사 결과가 아닙니다.', 10)
    fields = [
        ('장비 번호', device),
        ('장비 형식', 'DY CPB 32M'),
        ('소유 업체', '한빛중기 (시연)' if device != 'CPB-101' else '새봄중기 (시연)'),
        ('작성일', '2026. 07. 02.'),
        ('문서 번호', f'DEMO-{device}-' + ('NDT-20260702' if inspection else 'CERT-20260702')),
    ]
    y = h - 214
    for key, value in fields:
        text(44, y, key, 11, '#50616B')
        text(180, y, value, 12)
        c.setStrokeColorRGB(0.81, 0.85, 0.87)
        c.line(44, y - 14, w - 44, y - 14)
        y -= 48
    text(44, y - 16, '검사 범위와 기록' if inspection else '주요 장비 정보', 17)
    rows = [
        ('확인 부위', '붐 연결부 / 마스트 연결부'),
        ('검사 방법', '시연용 외관 확인 및 기록 예시'),
        ('기록 결과', '샘플 기록 - 적합 여부 판단에 사용 불가'),
    ] if inspection else [
        ('장비 용도', '현장 콘크리트 타설'),
        ('붐 길이', '32 m (시연용 제원)'),
        ('전원', '3상 380 V (시연용 제원)'),
    ]
    y -= 62
    for key, value in rows:
        text(44, y, key, 11, '#50616B')
        text(180, y, value, 11)
        y -= 34
    text(44, 139, '열람 시 확인', 13)
    text(44, 114, '화면에서 선택한 호기와 이 문서의 장비 번호가 같은지 확인합니다.', 10)
    text(44, 94, '이 문서는 데모 열람을 위한 샘플이며 효력 있는 원본을 대체하지 않습니다.', 10)
    c.setStrokeColorRGB(0.81, 0.85, 0.87)
    c.line(44, 64, w - 44, 64)
    text(44, 42, 'BOOMEYES · 소유주 장비 서류 데모', 9)
    text(w - 77, 42, '1 / 1', 9)
    c.save()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--font', required=True)
    args = parser.parse_args()
    pdfmetrics.registerFont(TTFont('Korean', args.font))
    OUT.mkdir(parents=True, exist_ok=True)
    manifest = []
    with tempfile.TemporaryDirectory(prefix='owner-assets-') as temporary:
        for unit in [1, 2, 3, 4, 5, 101]:
            device = f'CPB-{unit:03}'
            name = device.lower()
            for kind in ['certificate', 'inspection']:
                target = OUT / f'{name}-{kind}.pdf' if kind == 'certificate' else Path(temporary) / f'{name}-{kind}.pdf'
                document(target, device, kind == 'inspection')
                reader = PdfReader(target)
                content = reader.pages[0].extract_text()
                assert device in content and '시연용' in content and len(reader.pages) == 1
                subprocess.run(['pdftoppm', '-singlefile', '-scale-to', '1440', '-png', str(target), str(OUT / f'{name}-{kind}')], check=True)
                manifest.append({'device': device, 'kind': kind, 'preview': f'{name}-{kind}.png', 'pages': 1, 'sample': True})
    (OUT / 'manifest.json').write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + '\n')
    urls = []
    for unit in [1, 2, 3, 4, 5, 101]:
        device = f'CPB-{unit:03}'
        name = device.lower()
        urls.append(f"  '{device}': {{ certificate: {{ pdf: new URL('./{name}-certificate.pdf', import.meta.url).href, preview: new URL('./{name}-certificate.png', import.meta.url).href }}, inspection: new URL('./{name}-inspection.png', import.meta.url).href }},")
    (OUT / 'index.ts').write_text('// Generated by tools/owner/assets.py. Explicit URLs let Vite emit both app bundles.\nexport const OWNER_ASSETS: Record<string, { certificate: { pdf: string; preview: string }; inspection: string }> = {\n' + '\n'.join(urls) + '\n};\n')
    print(f'Owner originals: 6 PDF + 12 PNG; 12 pages rendered and identity verified.')


if __name__ == '__main__':
    main()
